"""The starter programs in `examples/` against the scenes they are for (IP-10).

Every graded scene ships an OpenPLC starter (`examples/openplc/<scene>/`) and a
TIA Portal starter (`examples/tia/<scene>/`): I/O declared, logic empty. They
are generated by `tools/gen_starters.py`, and a starter is a promise a student
builds on without being able to check it -- Modbus carries no tag names, and a
DB member nobody maps is simply never exchanged. So this file reads the
*committed files* the way a student's toolchain would and holds them to three
authorities that do not come from the generator:

* the tag set the engine registers for the scene,
  `engine/fixtures/scene_tag_sets.json` (which `--self-test=scenes` holds the
  engine to, and `test_grade_templates.py` holds the grader to): every tag
  declared, with the right direction and type, and nothing else;
* the Modbus map the sidecar's own `modbus-tcp` driver serves for that tag
  set: every located address in every `.st`, and every size in every
  `mbconfig.cfg`;
* S7's standard-access layout rules, re-derived here from the SCL source's own
  member order, for every offset in every `snap7_mapping.json`.

And then that a fresh run of the generator reproduces every file, so a scene
that changes under a committed starter fails here rather than in a classroom.

`FACTORYFORGE_TAG_FIXTURE` points the whole file (and the generator) at a
different fixture, which is how a renamed tag is shown to fail it.
"""

from __future__ import annotations

import importlib.util
import json
import os
import re
import sys
from pathlib import Path

import pytest

from factoryforge_sidecar import drivers
from factoryforge_sidecar.grading import registry
from factoryforge_sidecar.tags import Tag, TagTable

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
TEMPLATES = ROOT / "engine" / "templates"
FIXTURE = Path(os.environ.get("FACTORYFORGE_TAG_FIXTURE")
               or ROOT / "engine" / "fixtures" / "scene_tag_sets.json")

SCENES = sorted(registry.rubrics())

_IEC_TYPE = {"bit": "BOOL", "int": "DINT", "float": "REAL"}
_S7_TYPE = {"bit": "Bool", "int": "DInt", "float": "Real"}


def _gen():
    """`tools/gen_starters.py`, imported by path (tools/ is not a package).
    Registered in sys.modules first: its dataclasses look their module up."""
    if "gen_starters" not in sys.modules:
        spec = importlib.util.spec_from_file_location("gen_starters", ROOT / "tools" / "gen_starters.py")
        module = importlib.util.module_from_spec(spec)
        sys.modules["gen_starters"] = module
        spec.loader.exec_module(module)
    return sys.modules["gen_starters"]


def _read(path: Path) -> str:
    # git on Windows checks these out with CRLF; the content is what matters.
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def _stem(scene: str) -> str:
    return scene.replace("-", "_")


# --- the authorities ---------------------------------------------------------

def _fixture(scene: str) -> dict[str, tuple[str, str]]:
    """`{tag id: (type, kind)}` the engine registers for *scene*."""
    tags = json.loads(FIXTURE.read_text(encoding="utf-8"))["scenes"][scene]
    return {t["id"]: (t["type"], t["kind"]) for t in tags}


def _commanded(scene: str) -> set[str]:
    """Tags a part in the template drives itself, which the program must never
    write: a motor starter's `load_tag`. Read from the template here rather
    than taken from the generator, so the exception is not self-certified."""
    manifest = {e["id"]: e for e in json.loads(
        (TEMPLATES / "manifest.json").read_text(encoding="utf-8"))}
    path = manifest[scene]["path"]
    if not path:
        return set()
    data = json.loads((TEMPLATES / path.removeprefix("res://templates/")).read_text(encoding="utf-8"))
    return {p["properties"]["load_tag"] for p in data["parts"]
            if p["type"] == "MotorStarter" and p.get("properties", {}).get("load_tag")}


class _SilentBus:
    def on_describe(self, _handler) -> None:
        pass

    on_update = on_disconnect = on_describe

    async def status(self, *args, **kwargs) -> None:
        pass


async def _served(scene: str) -> dict[str, tuple[str, int, int]]:
    """What `modbus-tcp` really serves for this tag set on a fresh sidecar."""
    table = TagTable([Tag(tid, tid, ty, kind) for tid, (ty, kind) in _fixture(scene).items()])
    driver = drivers.create("modbus-tcp", _SilentBus(), port=0)
    await driver.rebuild(scene, 1, table)
    return {m.tag_id: (m.block, m.address, m.width) for m in driver._by_tag.values()}


# --- reading the starters as a toolchain would -------------------------------

_LOCATED = re.compile(
    r"^\s*(\w+)\s+AT\s+%([IQ])([XW])([\d.]+)\s*:\s*(\w+)\s*;\s*\(\*\s*(\S+)\s+(\dx\d+)", re.M)
_UNLOCATED = re.compile(r"^\s*(\w+)\s*:\s*(DINT|REAL)\s*;\s*\(\*\s*(\S+)", re.M)


def _program(scene: str) -> str:
    text = _read(EXAMPLES / "openplc" / scene / f"{_stem(scene)}.st")
    match = re.search(r"^PROGRAM\s+\w+\s*$(.*?)^END_PROGRAM", text, re.S | re.M)
    assert match, f"{scene}: no PROGRAM ... END_PROGRAM in the .st"
    return match.group(1)


def _st(scene: str):
    """`(located, unlocated)`: `[(name, 'I'|'Q', 'X'|'W', index, type, tag, label)]`
    and `[(name, type, tag)]`, from the PROGRAM's declarations only."""
    body = _program(scene)
    return _LOCATED.findall(body), _UNLOCATED.findall(body)


def _without_comments(text: str) -> str:
    return re.sub(r"\(\*.*?\*\)", " ", text, flags=re.S)


def _mbconfig(scene: str) -> dict[str, int]:
    text = _read(EXAMPLES / "openplc" / scene / "mbconfig.cfg")
    return {key: int(value) for key, value in re.findall(r'^device0\.(\w+)\s*=\s*"(\d+)"', text, re.M)}


_SCL_MEMBER = re.compile(
    r"^\s*(\w+)\s*:\s*(Bool|DInt|Real)\s*;\s*//\s*(\S+)\s+\((PLC writes|PLC reads)\)", re.M)


def _scl_members(scene: str) -> list[tuple[str, str, str, str]]:
    """`[(member, S7 type, tag id, direction)]` in declaration order."""
    text = _read(EXAMPLES / "tia" / scene / f"{_stem(scene)}.scl")
    db = re.search(r'^DATA_BLOCK "FF_IO"(.*?)^END_DATA_BLOCK', text, re.S | re.M)
    assert db, f"{scene}: no DATA_BLOCK \"FF_IO\" in the .scl"
    assert "S7_Optimized_Access := 'FALSE'" in db.group(1), (
        f"{scene}: FF_IO must be a standard-access DB, or snap7 has no offsets to use")
    return _SCL_MEMBER.findall(db.group(1))


def _mapping(scene: str, name: str) -> dict[str, str]:
    data = json.loads(_read(EXAMPLES / "tia" / scene / name))
    return {k: v for k, v in data.items() if not k.startswith("_")}


# --- which scenes ------------------------------------------------------------

def test_every_graded_scene_has_both_starters_and_there_are_no_others():
    for kind in ("openplc", "tia"):
        have = sorted(p.name for p in (EXAMPLES / kind).iterdir() if p.is_dir())
        assert have == SCENES, f"examples/{kind}/ has starters for {have}, the grader marks {SCENES}"


# --- OpenPLC -----------------------------------------------------------------

@pytest.mark.parametrize("scene", SCENES)
def test_the_st_starter_declares_exactly_the_scene_tag_set(scene):
    """Ids, direction and type, one message per tag that is wrong."""
    expected = _fixture(scene)
    hands_off = _commanded(scene)
    located, unlocated = _st(scene)
    by_tag: dict[str, list] = {}
    for row in located:
        by_tag.setdefault(row[5], []).append(row)
    wide = {tag: (name, ty) for name, ty, tag in unlocated}

    problems = []
    for tag_id, (ty, kind) in sorted(expected.items()):
        rows = by_tag.get(tag_id, [])
        if tag_id in hands_off:
            if rows or tag_id in wide:
                problems.append(f"{tag_id} is driven by a motor starter and must not be wired")
            continue
        io = "I" if kind == "input" else "Q"
        if ty == "bit":
            if len(rows) != 1 or rows[0][1:3] != (io, "X") or rows[0][4] != "BOOL":
                problems.append(f"{tag_id} ({ty}/{kind}) should be one BOOL at %{io}X, "
                                f"is {[(r[0], '%' + r[1] + r[2] + r[3], r[4]) for r in rows]}")
            continue
        halves = sorted(rows, key=lambda r: int(r[3]))
        if (len(halves) != 2 or any(r[1:3] != (io, "W") or r[4] != "WORD" for r in halves)
                or not halves[0][0].endswith("Hi") or not halves[1][0].endswith("Lo")
                or int(halves[1][3]) != int(halves[0][3]) + 1):
            problems.append(f"{tag_id} ({ty}/{kind}) should be two consecutive WORDs at "
                            f"%{io}W, high word first; is {[(r[0], '%' + r[1] + r[2] + r[3]) for r in rows]}")
        if wide.get(tag_id, (None, None))[1] != _IEC_TYPE[ty]:
            problems.append(f"{tag_id} ({ty}) should have a {_IEC_TYPE[ty]} variable, "
                            f"has {wide.get(tag_id)}")
    declared = set(by_tag) | set(wide)
    problems += [f"{tag_id} is declared but the scene has no such tag"
                 for tag_id in sorted(declared - set(expected))]
    assert not problems, f"{scene}:\n  " + "\n  ".join(problems)


@pytest.mark.parametrize("scene", SCENES)
async def test_every_st_address_is_the_one_the_sidecar_serves(scene):
    """An address off by one is worse than no starter: it drives the wrong
    device with nothing on either side to say so. So each located variable is
    checked against the driver's real allocation, through OpenPLC's own
    numbering (`updateBuffersIn_MB`: point n of a polled block is %IX(100 +
    n/8).(n mod 8) or %IW(100 + n), counted from the block's Start)."""
    served = await _served(scene)
    config = _mbconfig(scene)
    blocks = {("Q", "X"): ("coils", "Coils", "0x"), ("I", "X"): ("discrete_inputs", "Discrete_Inputs", "1x"),
              ("Q", "W"): ("holding_registers", "Holding_Registers", "4x"),
              ("I", "W"): ("input_registers", "Input_Registers", "3x")}
    located, _ = _st(scene)
    problems = []
    for name, io, width, index, _type, tag_id, label in located:
        block, key, prefix = blocks[(io, width)]
        start = config[f"{key}_Start"]
        if tag_id not in served:
            problems.append(f"{name} is declared for {tag_id}, which the sidecar does not serve")
            continue
        s_block, s_address, s_width = served[tag_id]
        slave = s_address + (1 if name.endswith("Lo") and s_width == 2 else 0)
        n = slave - start
        want = f"{100 + n // 8}.{n % 8}" if width == "X" else f"{100 + n}"
        if s_block != block or index != want:
            problems.append(f"{tag_id}: the sidecar serves it at {s_block}[{slave}], which "
                            f"OpenPLC calls %{io}{width}{want}; {name} is declared at %{io}{width}{index}")
        if label != f"{prefix}{slave}":
            problems.append(f"{tag_id}: {name}'s comment says {label}, the sidecar serves {prefix}{slave}")
    assert not problems, f"{scene}:\n  " + "\n  ".join(problems)


@pytest.mark.parametrize("scene", SCENES)
async def test_mbconfig_polls_every_wired_point_and_no_hands_off_one(scene):
    """Exactly the range the program declares: a size short of it leaves a
    variable that never changes, and a coil block that reaches a starter's
    load writes that tag on every poll -- which the guarded cell fails."""
    served = await _served(scene)
    config = _mbconfig(scene)
    hands_off = _commanded(scene)
    keys = {"coils": "Coils", "discrete_inputs": "Discrete_Inputs",
            "input_registers": "Input_Registers", "holding_registers": "Holding_Registers"}
    problems = []
    for block, key in keys.items():
        used = sorted(a for tid, (b, addr, w) in served.items() if b == block and tid not in hands_off
                      for a in range(addr, addr + w))
        start, size = config[f"{key}_Start"], config[f"{key}_Size"]
        want = (used[0], used[-1] - used[0] + 1) if used else (0, 0)
        if (start, size) != want and not (not used and size == 0):
            problems.append(f"{key}: Start {start} Size {size}, the wired points need {want}")
        for tid in hands_off:
            b, addr, w = served[tid]
            if b == block and size and addr < start + size and addr + w > start:
                problems.append(f"{tid} ({block}[{addr}]) is inside the polled range {start}..{start + size - 1}")
    if config.get("Holding_Registers_Read_Size", 0):
        problems.append("Holding_Registers_Read would shift every %IW after the input registers")
    assert not problems, f"{scene}:\n  " + "\n  ".join(problems)


@pytest.mark.parametrize("scene", SCENES)
def test_the_st_moves_every_32_bit_value_through_both_registers(scene):
    """The declarations can be right and the program still read half a number.
    Every wide input is rebuilt from its own Hi and Lo, with the function for
    its type; every wide output is split into its own Hi and Lo."""
    body = _without_comments(_program(scene))
    located, unlocated = _st(scene)
    kinds = _fixture(scene)
    problems = []
    for name, ty, tag_id in unlocated:
        if tag_id not in kinds:
            problems.append(f"{name} is declared for {tag_id}, which the scene does not have")
            continue
        if kinds[tag_id][1] == "input":
            fn = "FF_WORDS_TO_REAL" if ty == "REAL" else "FF_WORDS_TO_DINT"
            pattern = rf"^\s*{name}\s*:=\s*{fn}\(HI\s*:=\s*{name}Hi,\s*LO\s*:=\s*{name}Lo\);"
        else:
            fn = "FF_REAL_TO_DWORD" if ty == "REAL" else "DINT_TO_DWORD"
            pattern = (rf"^\s*Raw32\s*:=\s*{fn}\({name}\);\s*\n"
                       rf"\s*{name}Hi\s*:=\s*DWORD_TO_WORD\(SHR\(IN\s*:=\s*Raw32,\s*N\s*:=\s*16\)\);\s*\n"
                       rf"\s*{name}Lo\s*:=\s*DWORD_TO_WORD\(Raw32\);")
        if not re.search(pattern, body, re.M):
            problems.append(f"{tag_id}: no {fn} line moving {name} through {name}Hi/{name}Lo")
    assert not problems, f"{scene}:\n  " + "\n  ".join(problems)


@pytest.mark.parametrize("scene", SCENES)
def test_the_logic_is_left_to_the_student(scene):
    """No solutions (IP-10). Section 2 of the ST and the FB's body are
    comments and nothing else."""
    st = _program(scene)
    section = re.search(r"2\. Your program(.*?)=====\s*3\.", st, re.S)
    assert section, f"{scene}: the .st has no section 2"
    leftover = _without_comments("(*" + section.group(1) + "*)").strip()
    assert not leftover, f"{scene}: the .st's logic section contains {leftover!r}"

    scl = _read(EXAMPLES / "tia" / scene / f"{_stem(scene)}.scl")
    fb = re.search(r"^FUNCTION_BLOCK.*?^BEGIN$(.*?)^END_FUNCTION_BLOCK", scl, re.S | re.M)
    assert fb, f"{scene}: no FUNCTION_BLOCK body in the .scl"
    code = [line for line in fb.group(1).splitlines()
            if line.strip() and not line.strip().startswith("//")]
    assert not code, f"{scene}: the FB body contains {code}"


_FIRST_POLL = "**Every input reads FALSE until OpenPLC's first poll returns.**"


@pytest.mark.parametrize("scene", SCENES)
def test_an_openplc_starter_with_an_estop_warns_about_the_first_scans(scene):
    """IP-41, AGENTS.md gotcha 25. OpenPLC scans before its first Modbus poll
    returns and reads every input FALSE until then, so a normally closed
    E-stop looks struck and a trip latched on `NOT PanelEstop` trips itself on
    every start. The guide's program found that on a real OpenPLC; a student
    starting from a starter must be told before they find it the same way.
    Whether the scene has an E-stop comes from the engine's tag set, not the
    generator."""
    if "panel.estop" not in _fixture(scene):
        pytest.skip(f"{scene} has no panel.estop")
    readme = _read(EXAMPLES / "openplc" / scene / "README.md")
    start = readme.find("- " + _FIRST_POLL)
    assert start >= 0, f"{scene}: the OpenPLC README does not warn that the first scans read FALSE"
    bullet = re.split(r"\n(?=- |#)", readme[start:])[0]
    bullet = " ".join(bullet.split())
    for needle in ("`panel.estop`", "EstopSeen", "NOT PanelEstop", "docs/OPENPLC.md"):
        assert needle in bullet, f"{scene}: the first-scan warning does not mention {needle}"
    # Every other normally closed input the README's own I/O table lists.
    closed = re.findall(r"^\| `([\w.]+)` \| PLC reads \| bit \|[^\n]*normally closed", readme, re.M)
    assert "panel.estop" in closed, f"{scene}: the I/O table does not call panel.estop normally closed"
    for tag in closed:
        assert f"`{tag}`" in bullet, f"{scene}: the first-scan warning leaves out {tag}, normally closed"

    section = re.search(r"2\. Your program(.*?)=====\s*3\.", _program(scene), re.S)
    assert section, f"{scene}: the .st has no section 2"
    text = " ".join(section.group(1).split())
    assert "IF PanelEstop THEN EstopSeen := TRUE; END_IF;" in text, (
        f"{scene}: the .st's section 2 does not show the EstopSeen pattern")
    assert "EstopSeen AND NOT PanelEstop" in text, f"{scene}: the .st does not arm the trip on EstopSeen"


# --- TIA Portal --------------------------------------------------------------

@pytest.mark.parametrize("scene", SCENES)
def test_the_scl_db_declares_exactly_the_scene_tag_set(scene):
    expected = _fixture(scene)
    hands_off = _commanded(scene)
    members = _scl_members(scene)
    problems = []
    seen = {}
    for member, s7, tag_id, direction in members:
        if tag_id in seen:
            problems.append(f"{tag_id} is declared twice")
        seen[tag_id] = (s7, direction)
    for tag_id, (ty, kind) in sorted(expected.items()):
        if tag_id in hands_off:
            if tag_id in seen:
                problems.append(f"{tag_id} is driven by a motor starter and must not be in FF_IO")
            continue
        want = (_S7_TYPE[ty], "PLC writes" if kind == "output" else "PLC reads")
        if seen.get(tag_id) != want:
            problems.append(f"{tag_id} ({ty}/{kind}) should be {want}, is {seen.get(tag_id)}")
    problems += [f"{tid} is in FF_IO but the scene has no such tag" for tid in sorted(set(seen) - set(expected))]
    assert not problems, f"{scene}:\n  " + "\n  ".join(problems)


@pytest.mark.parametrize("scene", SCENES)
def test_the_opcua_and_plcsim_mappings_name_the_db_members(scene):
    """The mapping is what the driver exchanges. A member it names that the DB
    does not have is `bad_node`; a tag it leaves out is never exchanged."""
    members = {tag_id: member for member, _s7, tag_id, _d in _scl_members(scene)}
    opcua = _mapping(scene, "opcua_mapping.json")
    plcsim = _mapping(scene, "plcsim_mapping.json")
    assert set(opcua) == set(members), f"{scene}: opcua keys {sorted(set(opcua) ^ set(members))}"
    assert set(plcsim) == set(members), f"{scene}: plcsim keys {sorted(set(plcsim) ^ set(members))}"
    for tag_id, member in members.items():
        assert opcua[tag_id] == f'ns=3;s="FF_IO"."{member}"', (scene, tag_id, opcua[tag_id])
        assert plcsim[tag_id] == f"FF_IO.{member}", (scene, tag_id, plcsim[tag_id])


def _s7_offsets(members) -> dict[str, tuple[int, int | None, int]]:
    """Standard-access layout, from the SCL member order: `{tag: (byte, bit or
    None, size)}`. Bools pack eight to a byte from bit 0; a 4-byte DInt or
    Real starts on the next even byte. The same rules produced FF_IO's
    verified layout (examples/snap7_mapping.json: eight Bools, DBD2, DBD6)."""
    out, byte, bit = {}, 0, 0
    for _member, s7, tag_id, _d in members:
        if s7 == "Bool":
            out[tag_id] = (byte, bit, 1)
            bit += 1
            if bit == 8:
                byte, bit = byte + 1, 0
        else:
            if bit:
                byte, bit = byte + 1, 0
            if byte % 2:
                byte += 1
            out[tag_id] = (byte, None, 4)
            byte += 4
    return out


def test_the_s7_layout_rules_reproduce_the_verified_ff_io():
    """The layout function above is only an authority if it gets the one DB
    that was checked against a live CPU right."""
    doc = [("ConveyorRotate", "Bool", "conveyor.rotate", ""), ("EmitterEmit", "Bool", "emitter.emit", ""),
           ("PusherExtend", "Bool", "pusher.extend", ""), ("StackLightGreen", "Bool", "stack_light.green", ""),
           ("SensorLow", "Bool", "sensor_low.detect", ""), ("SensorHigh", "Bool", "sensor_high.detect", ""),
           ("PusherExtended", "Bool", "pusher.extended", ""), ("PusherRetracted", "Bool", "pusher.retracted", ""),
           ("CounterTall", "DInt", "counter.tall", ""), ("CounterShort", "DInt", "counter.short", "")]
    verified = json.loads(_read(EXAMPLES / "snap7_mapping.json"))
    for tag_id, (byte, bit, _size) in _s7_offsets(doc).items():
        assert verified[tag_id] == (f"DBX{byte}.{bit}" if bit is not None else f"DBD{byte}")


@pytest.mark.parametrize("scene", SCENES)
def test_the_snap7_offsets_follow_the_db_and_never_mix_directions(scene):
    members = _scl_members(scene)
    snap7 = _mapping(scene, "snap7_mapping.json")
    offsets = _s7_offsets(members)
    assert set(snap7) == set(offsets), f"{scene}: snap7 keys {sorted(set(snap7) ^ set(offsets))}"
    owner: dict[int, set[str]] = {}
    for _member, _s7, tag_id, direction in members:
        byte, bit, size = offsets[tag_id]
        want = f"DBX{byte}.{bit}" if bit is not None else f"DBD{byte}"
        assert snap7[tag_id] == want, f"{scene}: {tag_id} is at {want} in the DB, mapped to {snap7[tag_id]}"
        for b in range(byte, byte + size):
            owner.setdefault(b, set()).add(direction)
    shared = sorted(b for b, dirs in owner.items() if len(dirs) > 1)
    assert not shared, (f"{scene}: bytes {shared} hold both PLC- and simulator-written "
                        f"members; snap7 would read-modify-write the PLC's bits (gotcha 19d)")


# --- the generator -----------------------------------------------------------

def test_regenerating_the_starters_changes_nothing():
    """A stale starter fails here. Re-run `python tools/gen_starters.py` and
    commit what it writes."""
    gen = _gen()
    problems = gen.stale(gen.render_all(FIXTURE))
    assert not problems, "\n  ".join(["starters out of date:"] + problems)


def test_the_generator_is_deterministic():
    gen = _gen()
    assert gen.render_all(FIXTURE) == gen.render_all(FIXTURE)


# --- what a release user is told to run (IP-36) -------------------------------

#: A sidecar command at the start of a line, in any of the forms a page could
#: write it -- so the test sees the bare `factoryforge-sidecar connect` that
#: PowerShell and a Linux shell refuse, not only the forms that work.
_SIDECAR_COMMAND = re.compile(
    r"^\s*(?:#\s*|\(\*\s*)?((?:\.[\\/])?factoryforge-sidecar(?:\.exe)?)\s+"
    r"(?:connect|grade|demo|browse|drivers)\b")


def _release_text():
    sys.path.insert(0, str(ROOT / "tools" / "packaging"))
    import release_text
    return release_text


def test_no_starter_tells_a_release_user_to_run_what_the_release_lacks():
    """The generator used to write `python tools/grade.py` into every starter
    README; the zip has neither Python nor tools/."""
    rt = _release_text()
    problems = [f"{rel}:{line}: {message}"
                for rel, text in _gen().render_all(FIXTURE).items()
                for line, message in rt.command_problems(rel, text)]
    assert not problems, "\n".join(problems[:20])


def test_every_sidecar_command_a_starter_shows_runs_from_the_extracted_folder():
    """`.\\factoryforge-sidecar` (PowerShell and cmd.exe) or
    `./factoryforge-sidecar` (Linux), never the bare name, which neither
    PowerShell nor a Linux shell looks for in the current folder. The JSON
    `_usage` strings are values, not lines, so they are read one by one."""
    bare, seen = [], 0
    for rel, text in _gen().render_all(FIXTURE).items():
        lines = text.split("\n")
        if rel.endswith(".json"):
            lines = [v for k, v in json.loads(text).items() if k.startswith("_usage")]
        for number, line in enumerate(lines, 1):
            m = _SIDECAR_COMMAND.match(line)
            if not m:
                continue
            seen += 1
            if m.group(1) not in (".\\factoryforge-sidecar", "./factoryforge-sidecar"):
                bare.append(f"{rel}:{number}: {line.strip()}")
    assert seen > 100, f"only {seen} sidecar commands found -- is the pattern still right?"
    assert not bare, "\n".join(bare[:20])


def test_the_index_shows_the_grader_check_a_release_user_can_run_as_printed():
    """The lockstep reference runs are the one grading command a user with
    only the zip can run and see PASS and FAIL without a PLC; the release
    gate runs exactly these (`check_release.GATE_*`)."""
    index = _gen().render_all(FIXTURE)["examples/README.md"]
    for reference in ("good", "blind"):
        assert (f".\\factoryforge-sidecar grade --scene sorting-by-height "
                f"--reference {reference} --lockstep") in index, reference
